<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - LSI</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7d224f8b-1313-422f-8759-dde08a8fb563</testSuiteGuid>
   <testCaseLink>
      <guid>1ac74608-6c06-4eb3-a0b4-d96693d536fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/WINPOS_00204</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc887485-169d-4ceb-9ecd-982cbc366517</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad1ada4c-95ed-4fd1-a63c-77491f24d688</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e9446ea-62f8-43af-8f6a-36a6e9d6a4f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/WINPOS_00205</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5798563d-3244-485a-a618-9eac9649e8c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e88e721e-1755-4539-8767-1f95c7a5fe57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2917d00-aedb-47ea-961c-cec231b4acdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/WINPOS_00146</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9723d885-bcc3-4e23-a38c-0783f11ef213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b75c0c9b-25ab-4d40-bfa8-610353c6563c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5e634f3-0e0c-4c0c-a4d2-69c39924d4a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/WINPOS_00107</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>65d091b9-e678-4a3b-97f1-b63144424e27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/WINPOS_00159</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70043ec0-9608-4d1e-a57f-e85a55dff2f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff987eb8-de7c-4e09-8de8-475aeac81de8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>804000de-944f-4c74-9ba3-70dc2b17c83c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/WINPOS_00156</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95c322eb-b7dd-4084-83df-e151ebde9829</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4c903f2-7b64-4e8a-8a6f-8c1553c4e504</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
