<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_paymentQr</name>
   <tag></tag>
   <elementGuidId>8f99ee25-ec2e-43de-9323-d98401a77d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentqr-qr_string</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='paymentqr-qr_string']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Input QR String&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>05fd018c-80ec-48a6-bc36-04bdc1b759ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentqr-qr_string</value>
      <webElementGuid>dfea9d76-7181-45f2-b18d-49afad29783e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3c5f279c-d6c1-4f2f-bf89-1f29335131fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaymentQr[qr_string]</value>
      <webElementGuid>56389994-f295-4022-9a7b-5672a6b54592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>d216043d-e94a-465a-9c5b-6ac0c4227635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d6308183-8630-40d9-965c-65ca9a5ca8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a6497b9-1b08-46b3-9dc7-2a2dea3456da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentqr-qr_string&quot;)</value>
      <webElementGuid>eb425b10-78b5-4d0a-a4b8-198530f5df75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='paymentqr-qr_string']</value>
      <webElementGuid>ed49212c-b6e5-43a5-99cc-1e0d1f7ec384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div/div/textarea</value>
      <webElementGuid>206e26c3-3708-4f46-9e62-d8b612e3e9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3edb7c3b-be28-4ddc-8352-4b1caec725f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'paymentqr-qr_string' and @name = 'PaymentQr[qr_string]']</value>
      <webElementGuid>02873f5b-6c74-4582-8121-6b87d12f97c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
