<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_amountQR</name>
   <tag></tag>
   <elementGuidId>657e9050-3552-4023-9c0a-0f5a01304954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentqr-amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentqr-amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Amount&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89cacd6e-630f-4011-9ef0-2606cbbdf29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bbd42bd-c0d5-4fb4-bfaa-26111fdf973b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentqr-amount</value>
      <webElementGuid>fdc5140a-ed7d-4fc3-b949-5d740b429ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>693e9d6e-ca8e-49e2-aad0-c78306b176a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaymentQr[amount]</value>
      <webElementGuid>c6c883e4-f446-42b3-b253-2e6b3a3879d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f13e514-bcc3-4aed-b7ed-0a8b57324117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentqr-amount&quot;)</value>
      <webElementGuid>bde895dd-16eb-4042-b642-21f39c745e50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentqr-amount']</value>
      <webElementGuid>c9eaddd0-4bd5-4c0c-b399-53f7c593f5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div/div/div[4]/div/input</value>
      <webElementGuid>818e4e31-384c-419b-8c25-92953d94e734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>3b940c28-e48c-4cc4-9659-2ed54f72cd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'paymentqr-amount' and @name = 'PaymentQr[amount]']</value>
      <webElementGuid>ed8e5dfb-306e-4806-a567-136a4579fd2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
